<?php 

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function name_location_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function name_location_add_meta_box() {
	add_meta_box(
		'name_location-name-location',
		__( 'Name & Occupation', 'name_location' ),
		'name_location_html',
		'testimonials',
		'side',
		'high'
	);
}
add_action( 'add_meta_boxes', 'name_location_add_meta_box' );

function name_location_html( $post) {
	wp_nonce_field( '_name_location_nonce', 'name_location_nonce' ); ?>

	<p>
		<label for="name_location_name"><b><?php _e( 'Name', 'name_location' ); ?></b></label><br>
		<input class="widefat" ype="text" name="name_location_name" id="name_location_name" value="<?php echo name_location_get_meta( 'name_location_name' ); ?>">
	</p>	<p>
		<label for="name_location_location"><b><?php _e( 'Occupation', 'name_location' ); ?></b></label><br>
		<input class="widefat" type="text" name="name_location_location" id="name_location_location" value="<?php echo name_location_get_meta( 'name_location_location' ); ?>">
	</p>
	<p>
	<label for="name_location_location"><b><?php _e( 'Rating', 'name_location' ); ?></b></label><br>
	<span class="star-cb-group">
			<input type="radio" name="rating_description" id="rating_description_4" value="5" <?php echo ( name_location_get_meta( 'rating_description' ) === '5' ) ? 'checked' : ''; ?>>
	<label for="rating_description_4">5</label>

			<input type="radio" name="rating_description" id="rating_description_3" value="4" <?php echo ( name_location_get_meta( 'rating_description' ) === '4' ) ? 'checked' : ''; ?>>
	<label for="rating_description_3">4</label>

			<input type="radio" name="rating_description" id="rating_description_2" value="3" <?php echo ( name_location_get_meta( 'rating_description' ) === '3' ) ? 'checked' : ''; ?>>
	<label for="rating_description_2">3</label>

			<input type="radio" name="rating_description" id="rating_description_1" value="2" <?php echo ( name_location_get_meta( 'rating_description' ) === '2' ) ? 'checked' : ''; ?>>
	<label for="rating_description_1">2</label>
			
			<input type="radio" name="rating_description" id="rating_description_0" value="1" <?php echo ( name_location_get_meta( 'rating_description' ) === '1' ) ? 'checked' : ''; ?>>
	<label for="rating_description_0">1</label>
	 		<input type="radio" id="rating-0" name="rating" value="0" class="star-cb-clear" /><label for="rating-0">0</label>
	</span>
	</p>
	<?php
}

function name_location_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['name_location_nonce'] ) || ! wp_verify_nonce( $_POST['name_location_nonce'], '_name_location_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['name_location_name'] ) )
		update_post_meta( $post_id, 'name_location_name', esc_attr( $_POST['name_location_name'] ) );
	if ( isset( $_POST['name_location_location'] ) )
		update_post_meta( $post_id, 'name_location_location', esc_attr( $_POST['name_location_location'] ) );
	if ( isset( $_POST['rating_description'] ) )
		update_post_meta( $post_id, 'rating_description', esc_attr( $_POST['rating_description'] ) );
}
add_action( 'save_post', 'name_location_save' );

/*
	Usage: name_location_get_meta( 'name_location_name' )
	Usage: name_location_get_meta( 'name_location_location' )
	Usage: name_location_get_meta( 'rating_description' )
*/


 ?>